### ISSUE TITLE
added timeout but no indication of failing tests

### ISSUE THREAD

**Issue by walshe** [avajs/ava#1594] opened 2017-11-17 17:28 UTC
is there a way to tell it to print out name of failing test files ? 

  111 passed
  2 exceptions

  ✖ Exited because no new tests completed within the last 5000ms of inactivity

  ✖ Exited because no new tests completed within the last 5000ms of inactivity

**Comment by ace-n** [comment] 2017-11-20 08:19
Is this the same thing as #583, or something different?

**Comment by walshe** [comment] 2017-11-20 14:44
not really, 
but even if it was, i want to be able to detect the failing tests then an automated build is being run

**Comment by novemberborn** [comment] 2017-11-20 16:08
I'd say this is a duplicate of #583, yes. Closing it accordingly.



> i want to be able to detect the failing tests then an automated build is being run

Could you elaborate on this? Why does the proposed solution for #583 not solve your problem?

**Closed by novemberborn** 2017-11-20 16:08 UTC

**Comment by walshe** [comment] 2017-11-20 16:12
I could press ctrl+c if I was running in my own terminal sure, but what about an automated build by circleci for example ?

**Comment by ace-n** [comment] 2017-11-21 06:00
@walshe you mean failing due to timeout? (#583 covers both `CTRL-C` and timeouts.)

**Comment by ace-n** [comment] 2017-11-22 05:36
If you're talking about the `2 exceptions` part, I believe those are thrown by AVA itself to denote that some test files are pending - as opposed to outright test failures.

#583 would print the tests (and potentially the test files) that timed out.

Does that help at all?

**Comment by walshe** [comment] 2017-11-22 14:18
Im still not understanding - so what is the fix/flag I need to use?

**Comment by novemberborn** [comment] 2017-11-26 14:13
#583 is the issue that tracks improvements to the timeout feature, so that it would indeed show the pending tests when a timeout is detected. For now I'd run the test suite with the `--serial` flag to see track down the offending tests.
