### ISSUE TITLE
No warning re duplicate test names in same file.

### ISSUE THREAD

**Issue by odigity** [avajs/ava#1392] opened 2017-05-24 07:12 UTC
(This is either a minor bug report or a minor feature request, as you like.)

I just noticed I had two tests in the same file with the same name because I forgot to modify the second one's name after copy/pasting.

This made me wonder why AVA never alerted me to this situation, since it's easy to detect.  Seems like the kind of thing that would justify a warning, though not an error.  I can't think of a case where this situation would reflect the programmer's intent, so it would be helpful to point it out.

### Config

```json
{
  "devDependencies": {
    "ava": "^0.19.1"
  },
}

### Command-Line Arguments

```
ava -v
```

### Environment

```
$ node -e "var os=require('os');console.log('Node.js ' + process.version + '\n' + os.platform() + ' ' + os.release())"
Node.js v7.10.0
linux 4.10.0-21-generic
$ ava --version
0.19.1
$ npm --version
4.2.0
```

**Comment by sindresorhus** [comment] 2017-05-24 07:26
Agreed. This is a duplicate of https://github.com/avajs/ava/issues/1207.

I would recommend using our ESLint plugin, which has a rule for this already: https://github.com/avajs/eslint-plugin-ava/blob/master/docs/rules/no-identical-title.md

**Closed by sindresorhus** 2017-05-24 07:26 UTC
