### ISSUE TITLE
cli --config switch directory requirement doesn't make sense with yarn workspaces

### ISSUE THREAD

**Issue by sovanyio** [avajs/ava#2234] opened 2019-08-30 14:41 UTC
## Description
I have a monorepo setup that uses maven for overall build orchestration and have implemented yarn workspaces to ensure consistency across the sub-projects. Certain files (babel config, browserslist, eslint, editorconfig, and hopefully ava) are shared across these sub-projects and live outside of the sub-project. This leads to a directory structure that has a private `package.json` at the root to describe the workspaces, along with an arbitrary location for shared configurations. Most of the tooling plays along with this well when not using explicit resolution against an absolute node_modules directory local to the sub-project except for ava. It seems that this is by design, where ava requires the config to be next to the sub-project `package.json`. This behavior is contrary to what I would expect. Is there a specific reason that sharing configurations would be disallowed? IMO any weird path resolution issues should be expected when doing this, if that was a concern.

### Test Source

Create the following structure
```
  /project
    /sub-project
      package.json
    package.json
    ava.config.js
```
Where the root package.json utilizes yarn workspaces. The sub-project scripts should declare something like `ava --config ../ava.config.js`, this currently fails.

### Error Message & Stack Trace

```
✖ Config files must be located next to the package.json file
error Command failed with exit code 1.
```

### Command-Line Arguments

This is the actual path I am attempting to use:

```
ava --config ../../ava.config.js
```

## Relevant Links

[--config commit](https://github.com/avajs/ava/commit/2dae2bfaf4b4ae53700fa439f34923b5a2c35a83)

## Environment

```
Node.js v10.16.0
darwin 18.7.0
ava: 2.3.0
npm: 6.11.2
yarn: 1.17.3
```

**Comment by novemberborn** [comment] 2019-09-01 09:59
> IMO any weird path resolution issues should be expected when doing this, if that was a concern.

Yes that's the concern. See #2185.

This issue made me realize something, what do you think of https://github.com/avajs/ava/issues/2185#issuecomment-526904408?

Closing this as a duplicate of #2185.

**Closed by novemberborn** 2019-09-01 09:59 UTC
