### ISSUE TITLE
deepEqual ignores the order of `Map`s and `Set`s

### ISSUE THREAD

**Issue by tp** [avajs/ava#1380] opened 2017-05-11 14:29 UTC
## Description

By virtue of using `lodash.isEqual` for the `deepEqual` function, ava ignores the order of `Map`s and `Set`s.

I tried to raise this with the lodash project, but they don't see anything wrong with their approach: https://github.com/lodash/lodash/issues/3155

I view this differently, as the spec explicitly requires insertion order to be preserved when iterating.

So basically the JS `Map` and `Set` are *ordered* variants of these types.

How else is one supposed to actually created an `OrderedSet` if these basic building blocks are already unsupported?

### Test Source

```js
test('JS map structures are equal only equal if order is the same', (t) => {
  const mapA = new Map<string, number>([['a', 1], ['b', 2]]);
  const mapB = new Map<string, number>([['a', 1], ['b', 2]]);

  t.deepEqual(mapA, mapB, 'ava: Maps with equal content in same insertion order compare as equal');
  t.true(_.isEqual(mapA, mapB), 'lodash: Maps with equal in same insertion order content compare as equal');

  // same map content, different order
  const mapC = new Map<string, number>([['b', 2], ['a', 1]]);

  t.notDeepEqual(mapA, mapC, 'ava: Maps with equal content but different insertion order compare as not equal');
  // t.false(_.isEqual(mapA, mapC), 'lodash: Maps with equal but different insertion order content compare as not equal');
});
```

### Error Message & Stack Trace

```
mapA:  Map { 'a' => 1, 'b' => 2 }
mapC:  Map { 'b' => 2, 'a' => 1 }
  ✖ equality-tests-map › JS map structures are equal only equal if order is the same ava: Maps with equal content but different insertion order compare as not equal
  
  1 test failed [16:26:36]



  equality-tests-map › JS map structures are equal only equal if order is the same
  equality-tests-map.ts:31

   31:   t.notDeepEqual(mapA, mapC, 'ava: Maps with equal content but different insertion order compare a…
   32:   // t.false(_.isEqual(mapA, mapC), 'lodash: Maps with equal but different insertion order content…

  ava: Maps with equal content but different insertion order compare as not equal

  Value is deeply equal:

    Map {
      a => 1,
      b => 2,
    }
```

**Comment by tp** [comment] 2017-05-11 14:49
Just saw that a similar concern was already raised in #1341.

Glad to see you are aware!

Not sure though if this will definitely be fixed by the aforementioned ticket, as it was just mentioned as the trigger, not necessarily the solution.

If it is included for sure, feel free to close this one.

**Comment by novemberborn** [comment] 2017-05-11 15:27
Yep, this is one of the things I'm hoping to fix with #1341. Will leave this open until then, thanks for raising it.

**Comment by novemberborn** [comment] 2017-06-28 13:00
#1341 has landed. A new release will be out soon.

**Closed by novemberborn** 2017-06-28 13:00 UTC

**Comment by shovon** [comment] 2018-04-12 18:54
I see @tp's point.

But a question about how to handle the assumption of unordered maps and sets (which is what many of us use it for, and why lodash ignores the ordering):

What is a good, idiomatic way to test for only elements in a Set and Map, without regard for ordering?

`t.deepEqual` seems to be out of the question.

@novemberborn any help? :)

**Comment by shovon** [comment] 2018-04-12 21:26
Here's my humble counter argument to @tp's point: object keys are also iterated in an ordered fashion, [as formalized in ES6's spec](https://esdiscuss.org/topic/nailing-object-property-order). According to the rationale in the original patch, then the following is an expected behaviour:

```
const objA = { a: 1, b: 2 };
const objB = { b:2, a: 1 };

t.deepEqual(objA, objB); // ERROR!
```

However, that is not the case, and `t.deepEqual(objA, objB)` will not yield an error.

I think this should be same for `Set`s and `Map`s, don't you think?

/cc @novemberborn

**Comment by novemberborn** [comment] 2018-04-13 08:35
@shovon there is no one right answer here. For AVA we've decided that order is relevant.

It's a bit more work to compare values out of order, but you could do something like this:

```js
t.is(mapA.size, mapB.size)
for (const [key, value] of mapA) {
  t.true(mapB.has(key))
  t.deepEqual(value, mapB.get(value))
}
```
