### ISSUE TITLE
[PROPOSAL] Support a "ava.config.js" file to make config portable

### ISSUE THREAD

**Issue by danawoodman** [avajs/ava#1626] opened 2018-01-03 22:03 UTC
## Description

I propose that ava support a configuration file (e.g. `ava.config.js`) which is similar to the `package.json` configuration. This file would make it more obvious where configuration lives as well as making it more portable since the `ava.config.js`file could just be copied over to a new project; no editing of `package.json` needed. Plus, it's a bit of good marketing since people looking at the source of a project would notice the config file. Win-win-win. 

There is a great package, [cosmiconfig](https://github.com/davidtheclark/cosmiconfig), which allows for both `package.json` config, `ava.config.js` and a `.avarc` file depending on the user's preferences. Prettier just added it and it makes adoption a lot easier for the end user.

## Relevant Links

- [cosmiconfig](https://github.com/davidtheclark/cosmiconfig)

**Comment by sindresorhus** [comment] 2018-01-03 22:32
Duplicate of #520

**Closed by sindresorhus** 2018-01-03 22:32 UTC
