### ISSUE TITLE
Node.js 12.5: process.stderr.hasColors is not a function

### ISSUE THREAD

**Issue by rauschma** [avajs/ava#2173] opened 2019-07-02 19:50 UTC
## Description

If I run a minimal test, I get:

```
  Error thrown in test:

  TypeError {
    message: 'process.stderr.hasColors is not a function',
  }
```

I think it is an issue with Node.js 12.5, because downgrading to 12.4 fixes it.

### Test Source

`test.mjs`:

```js
import test from 'ava';
import {strict as assert} from 'assert';

test('T', t => {
  assert.equal('a', '');
});
```

### Error Message & Stack Trace

There is no stack trace:

```
  Error thrown in test:

  TypeError {
    message: 'process.stderr.hasColors is not a function',
  }
```

### Config

All of `package.json` is relevant in this case (due to how I use `esm`):

```json
{
  "private": true,
  "scripts": {
    "test": "ava"
  },
  "dependencies": {
    "ava": "^2.1.0",
    "esm": "^3.2.25"
  },
  "// ava": [
    "failWithoutAssertions must be false, because assert.* is not tracked by AVA",
    "esm completely replaces Babel, which is switched off via babel:false and compileEnhancements:false"
  ],
  "ava": {
    "babel": false,
    "compileEnhancements": false,
    "extensions": [
      "mjs"
    ],
    "require": [
      "esm"
    ],
    "failWithoutAssertions": false
  }
}
```

### Command-Line Arguments

I run AVA without any command line arguments.

## Environment

* Node.js v12.5.0
* macOS: darwin 18.6.0
* AVA: 2.1.0
* npm: 6.9.0

**Comment by sindresorhus** [comment] 2019-07-02 20:12
Duplicate of #2170

**Closed by sindresorhus** 2019-07-02 20:12 UTC
