### ISSUE TITLE
Should `process.cwd()` be changed to the directory of the currently running test?

### ISSUE THREAD

**Issue by sindresorhus** [avajs/ava#32] opened 2015-09-01 16:01 UTC
Currently the cwd is the directory you execute `ava` in, but `ava` can be executed from any upper level in the project and will search down for test files, so the cwd is pretty arbitrary and useless. I want to make the cwd actually useful.

There are two options:

1.  Change cwd to root of the project. (This is what gulp/grunt does)
2.  Change cwd to the directory of the currently running test file. (This is what I personally prefer)

The reason I prefer the latter is that we *run* the test files hence IMHO the cwd is where we run it. It's like we would do: `cd tests && node test.js`.

-

Currently you have to do this to be able to load a read a test relative file:

```js
var path = require('path');
var fs = require('fs');
fs.readFileSync(path.join(__dirname, 'foo.json'));
```

If we changed `process.cwd()` to the currently running test directory we could instead just do:

```js
var fs = require('fs');
fs.readFileSync('foo.json');
```

-

Thoughts? Anything I'm missing?

**Comment by sindresorhus** [comment] 2015-09-01 16:03
@Qix- @kevva @vdemedes @mdibaiee @mattdesl @arthurvr

**Comment by Qix-** [comment] 2015-09-01 18:27
It sounds good, but it might make migrating from Mocha a bit of a pain. New projects will benefit from it; ones coming from Mocha won't.

**Comment by sindresorhus** [comment] 2015-09-01 18:38
@Qix- Why? It will make no difference if you've already hard-coded your paths with `__dirname`.

**Comment by Qix-** [comment] 2015-09-01 19:38
True. Those that haven't should be anyway.

**Comment by vdemedes** [comment] 2015-09-03 06:37
As for me, I think overriding core libraries/methods is always a bad idea. You never know what and how many things rely on that method.

Also, this is not that big of an issue to include test directory in paths.

**Comment by sindresorhus** [comment] 2015-09-03 06:50
Not going to override anything. This about using [`process.chdir()`](https://nodejs.org/api/process.html#process_process_chdir_directory) to set the cwd.

**Comment by vdemedes** [comment] 2015-09-03 06:51
Oh damn, what a shame :D Then I am all for it! :+1: Also tired of `join(__dirname, 'fixtures', 'shit')`

**Comment by sindresorhus** [comment] 2015-09-23 16:58
Currently the cwd is the directory you execute `ava` in, but `ava` can be executed from any upper level in the project and will search down for test files, so the cwd is pretty arbitrary and useless. I want to make the cwd actually useful.

There are two options:

1.  Change cwd to root of the project. (This is what gulp/grunt does)
2.  Change cwd to the directory of the currently running test file. (This is what I personally prefer)

The reason I prefer the latter is that we *run* the test files hence IMHO the cwd is where we run it. It's like we would do: `cd tests && node test.js`.

**Comment by kevva** [comment] 2015-10-06 19:29
Yeah, I like option two too because that's really what is expected. Using the project root would confuse me.

**Comment by arthurvr** [comment] 2015-10-06 19:32
> Yeah, I like option two too because that's really what is expected. Using the project root would confuse me.

Me too. :+1:

**Comment by stevemao** [comment] 2015-10-13 04:04
I think this is more intuitive for people who haven't used mocha. But would this confuse people who just learned `require(./)` and `fs.readFile(./)` as the path are relative to different base?

**Comment by sindresorhus** [comment] 2015-10-13 04:20
> But would this confuse people who just learned require(./) and fs.readFile(./) as the path are relative to different base?

That's not correct. If you start the node script from the file location they're the same. The point is that running a test is kinda like doing `node test.js` from the test file location.

**Comment by stevemao** [comment] 2015-10-13 04:24
> That's not correct. If you start the node script from the file location they're the same. The point is that running a test is kinda like doing node test.js from the test file location.

True, very intuitive because this is what I thought when I first used mocha :)

**Comment by jamestalmage** [comment] 2016-04-26 02:43
I have been pretty consistently been annoyed by this "feature". Yes `require(../some/path)` is relative, but if I am using `require` - it's at the top of my test, and easy to find. If I am using `cwd`, well, that could be anywhere. And it's not always easy to search for:

```js
// relies on cwd - but it isn't apparent how use my IDE's search tool to find it.
execa('node foo.js');
```

Moving a test that relies on `child_process.exec` or `execa` wreaks havoc since we implemented this.

Conversely paths relative to the module file are pretty easy to locate. Look for `__dirname` and `require` (`./` if things get really desperate). If I am moving a test file around (and not moving some resource with it) the search and replace is pretty easy.

--

I would have preferred that `cwd` was always set to to the same directory as `package.json` (found via `pkgUp`). That has the advantage of keeping `cwd` consistent, even when you execute `ava` from a subdir, and it allows you to treat `cwd` as a base for creating "intra-project-absolute paths".

**Comment by sindresorhus** [comment] 2016-04-26 07:30
@jamestalmage I agree. In hindsight, it was a bad idea with good intentions. Too bad it didn't show its downsides until much later. I've personally been bitten by this on multiple occasions too and seen some problems with it in the ecosystem. I think we should reconsider. I've never seen anyone other than me use it anyways (I've looked at a gadzillion open source AVA test files).

Some known problems this feature caused:

- https://github.com/sindresorhus/ava/issues/175
- https://github.com/istarkov/babel-plugin-webpack-loaders/issues/41
- https://github.com/sindresorhus/ava/pull/531 (had to absolutify paths from NODE_PATH becuase of the `cwd` change)
- https://github.com/sindresorhus/ava/issues/707 (would resolve this issue)

-

@vdemedes @novemberborn @sotojuan @jedrichards @istarkov @alexbooker @MarkHerhold @KidkArolis

**Comment by novemberborn** [comment] 2016-04-26 08:33
Relative imports are more cumbersome than relative file paths. I like setting `cwd` to the `package.json` directory, though that might be a little tricky for monorepo's.

**Comment by jamestalmage** [comment] 2016-04-26 09:37
> though that might be a little tricky for monorepo's

Not sure why it would be. Usually there is a `package.json` for each package in the monorepo - so it would just be relative to that. If there's not (some people auto-generate at deploy time) then you would be relative to the root `package.json`.

**Comment by sindresorhus** [comment] 2016-05-02 06:43
Ok, we're going to do this.

**Comment by sindresorhus** [comment] 2016-05-13 09:41
We might need some codemods for this change: https://github.com/jamestalmage/ava-codemods/issues/19

**Comment by novemberborn** [comment] 2016-05-22 16:40
@a-s-o let's discuss your suggestion here, not in https://github.com/avajs/ava-codemods/issues/19#issuecomment-220839269 :)

> Hi, may I also request not using the nearest package.json as the CWD (i.e looking package.json upwards from the test file). This may cause issues in multi-package repos where the test runner is in the root but there are multiple packages with their own package.json in the project (example the [babel](https://github.com/babel/babel) repo).

> I would like to suggest sticking with the directory where ava command is executed as that is the most obvious.

Currently we look at the `package.json` to load AVA config. We start the search for this file in the current working directory, so if you're executing AVA in the monorepo root, it would use the root's `package.json`. I imagine we'll do the same when determining the CWD for the test files.

Is this what you mean by "sticking with the directory where ava command is executed"?

**Comment by a-s-o** [comment] 2016-05-22 17:14
> Is this what you mean by "sticking with the directory where ava command is executed"?

I think you have it right, but to clarify, let's say I have the following directory structure

```
project_root
  +-- api
  |     +-- tests
  |     |     |-- api_test_1.js
  |     |     |-- api_test_2.js
  |     |-- api.js
  |     |-- package.json
  |
  |-- package.json
```
So, my suggestions is as follows:
> ~/project_root > ava **/tests/*.js         <-- process.cwd should be ~/project_root
> ~/project_root/api > ava **/tests/*.js   <-- process.cwd should be ~/project_root/api

Basically, cwd should be the working directory where the command was launched.

Hope that helps

**Comment by novemberborn** [comment] 2016-05-22 17:25
> So, my suggestions is as follows:

That's how it would work, but due to the presence of the `package.json`.

> Basically, cwd should be the working directory where the ava command was launched.

That becomes a problem when you launch `ava` from `project_root/api/tests`. We try to pick a consistent directory no matter where you start the tests from. Originally that was the directory the test file was in, but now it'll be the directory the `package.json` is in.

This behavior breaks down a little for monorepos with multiple `package.json` files, but to be fair so does `npm test` which doesn't look past the first `package.json` file.

**Comment by jamestalmage** [comment] 2016-05-22 17:57
We could add a `cwd` config option to `package.json`

**Comment by a-s-o** [comment] 2016-05-22 18:08
You are right, that is the default npm behaviour. Okay then that is a good
enough convention to follow. I can live with that. Thanks for the info.

**Comment by jamestalmage** [comment] 2016-06-22 20:58
Another bug caused by our current behavior: https://github.com/dtinth/babel-plugin-__coverage__/issues/39

We should revert this for the next release.

**Comment by KidkArolis** [comment] 2016-08-15 19:38
What's the status of this, changing cwd to the test file location is really annoying.

**Comment by sindresorhus** [comment] 2016-08-15 20:56
It's blocked on having a migrate script: https://github.com/avajs/ava/issues/32#issuecomment-218998130 The change itself is simple.

**Comment by shinzui** [comment] 2016-08-18 14:44
@sindresorhus I don't think the codemod should block this issue. I just started using ava and I wasted a lot of time figuring out why hapi was not loading my models correctly in the tests. I initially blamed hapi-shelf (plugin to load bookshelf models), but after tracing the code I discovered this issue and easily fixed my test to work around it.

**Comment by sindresorhus** [comment] 2016-08-18 15:07
Yeah, let's just do the change. 

It's hard to do a codemod for this correctly anyway, and I don't think it's important enough to force us to continue having surprising behavior for new users.

@avajs/core ?

**Comment by novemberborn** [comment] 2016-08-19 09:00
👍

**Comment by wmertens** [comment] 2016-09-30 11:33
So is anybody working on this? I'm not volunteering, just doing a "ping" 😀

**Comment by sindresorhus** [comment] 2016-10-03 15:36
@wmertens https://twitter.com/slicknet/status/782274190451671040

**Comment by novemberborn** [comment] 2016-10-18 08:12
Fixed by 476c65396155a7d16fbdd55c65863ecaabd873de.

**Closed by novemberborn** 2016-10-18 08:12 UTC
Labels: enhancement, help wanted, priority, question

**Comment by f593** [comment] 2020-01-28 01:21
Open

**Comment by f593** [comment] 2020-01-28 01:21
5
