### ISSUE TITLE
can't work in Lerna monorepo

### ISSUE THREAD

**Issue by fisker** [avajs/ava#2187] opened 2019-07-15 09:27 UTC
## Description

AVA not working as expected.

I've created a minimal repo, to reproduce this issue.

the repo for reproduction: https://github.com/fisker/ava-bug-with-lerna
ci ran result: https://travis-ci.org/fisker/ava-bug-with-lerna/builds/558815154

In this Lerna monorepo, I use yarn to install `AVA` at root dir, put a `test.js`(https://github.com/fisker/ava-bug-with-lerna/blob/master/packages/package1/test.js) file in `packages/package1/`, and `test` script(https://github.com/fisker/ava-bug-with-lerna/blob/c76aa131d3e4539150308a45ee0ae811a08f2c46/packages/package1/package.json#L10) add in `packages/package1/package.json`, when I run `lerna run test`, test should fail, but it's not.

I've tried to locate the problem, seems It's because this importLocal here

https://github.com/avajs/ava/blob/245148417817ffeaf1754cbb22ccf0adc83f8d1b/cli.js#L7

returns an empty object.

If this is not a bug, what is the right way to do this?

**Comment by novemberborn** [comment] 2019-07-15 19:36
We upgraded `import-local` in 2.2.0, could you check with 2.1.0 instead? Perhaps there's been a regression in that package our tests didn't pick up.

**Comment by fisker** [comment] 2019-07-16 00:51
@novemberborn 2.1.0 works, see https://travis-ci.org/fisker/ava-bug-with-lerna/builds/559203759

**Comment by novemberborn** [comment] 2019-07-16 08:04
@mxmul I suspect this is due to the `import-local` bump we did in 2.2.0. Could you shed any light on this? Thanks!

**Comment by fisker** [comment] 2019-07-16 09:28
I just found there is a same issue reported https://github.com/sindresorhus/import-local/issues/6 , and there is already a PR.

**Comment by novemberborn** [comment] 2019-07-18 08:49
> I just found there is a same issue reported [sindresorhus/import-local#6](https://github.com/sindresorhus/import-local/issues/6) , and there is already a PR.

Nice find, thanks!

**Comment by novemberborn** [comment] 2019-07-24 08:36
`import-local` 3.0.2 is out with a fix. If you have a package lock, uninstall and then reinstall AVA to refresh the dependency. The next AVA release will require the 3.0.2 release as the minimal version.

**Comment by fisker** [comment] 2019-07-26 06:09
yes, I have confirmed this is fixed by `import-local@3.0.2`

**Comment by revelt** [comment] 2019-08-27 16:25
should we close this issue if it's fixed?  @fisker @novemberborn ?

**Closed** 2019-08-27 16:32 UTC
Labels: bug, help wanted
