### ISSUE TITLE
Consider using babel-preset-env

### ISSUE THREAD

**Issue by SimenB** [avajs/ava#1101] opened 2016-11-03 09:33 UTC
## Description

Instead of rolling your own preset config checking node version (https://github.com/avajs/ava/blob/master/lib/babel-config.js#L43-L52), just have `preset: ['env']`.

https://github.com/babel/babel-preset-env/pull/35

I can provide a PR if you want it?

**Comment by sindresorhus** [comment] 2016-11-03 09:42
Duplicate of https://github.com/avajs/ava/issues/1101. I'd like to see it mature more first.

**Closed by sindresorhus** 2016-11-03 09:42 UTC

**Comment by SimenB** [comment] 2016-11-03 09:59
Duplicate of itself? I suppose #148 is the one, or #1068.

**Comment by sindresorhus** [comment] 2016-11-03 10:12
Ah yes
