### ISSUE TITLE
Output from `t.throws()` failing is missing a message

### ISSUE THREAD

**Issue by sindresorhus** [avajs/ava#1342] opened 2017-04-05 15:04 UTC
With latest master (ecdadfa9c2b5d5c40e4edd14df0319f222007c60).

```
import test from 'ava';

const foo = () => Promise.resolve('foo');

test(async t => {
	await t.throws(foo());
});
```

Outputs:

```
  1 failed

  [anonymous]
  /Users/sindresorhus/dev/private/ava-playground/test.js:6

   5: test(async t => {
   6:   await t.throws(foo());
   7: });

  Test.<anonymous> (test.js:6:10)
  step (test.js:9:191)
  Test.<anonymous> (test.js:9:99)
  Test.fn (test.js:5:1)
```

**Comment by novemberborn** [comment] 2017-04-05 15:33
This works:

```js
test(async t => {
	await t.throws(foo(), null, 'foo');
});
```

I think what you're saying is that we should *always* print something like "Expected promise to be rejected, but it was resolved instead." And then if the message is provided add it. Like:

```
  [anonymous]
  /private/var/folders/_6/p8qxp_3n62zg9081tvb0lcc80000gn/T/tmp.Vm1UQYRgMc/test.js:10

    9: test(t => {
   10:   t.true(false, 'hi')
   11: })

  hi

  Value is not `true`:

    false
```

**Comment by sindresorhus** [comment] 2017-04-05 15:38
Sorry for being unclear, by message, I meant explanation, not the `message` argument.

> I think what you're saying is that we should always print something like "Expected promise to be rejected, but it was resolved instead."

I would also include the value for completeness:

> Expected promise to be rejected, but it was resolved with "foo" instead.

**Comment by novemberborn** [comment] 2017-04-05 15:40
Yes that sounds good.

**Comment by tdeschryver** [comment] 2017-06-07 20:49
I've tried to solve this issue, but I've hit a point where I need some validation/input from someone with experience.
- Because we need the value of the promise, is it OK to replace the `noop` method at [lib/assert.js#L177](https://github.com/tdeschryver/ava/blob/message_throws/lib/assert.js#L177) and use the resolved value to call `fail`?
- Is it correct that `fail(this, new AssertionError())` is being called or is `throw new AssertionError()` a better solution?
- I've tested the solution with the snippet from this issue and the message as you can see below is being shown (I think this is the expected behavior?), but the new test at [test/assert.js#L651](https://github.com/tdeschryver/ava/blob/message_throws/test/assert.js#L651) is failing because `lastFailure` is `null` (because its a promise?). What would a good way to fix this? I'm thinking about creating a `failsWith` method for promises, but there must be a better way...
```
Expected promise to be rejected, but it was resolved instead
Resolved with:
"foo"
```
- Is it OK if I'm continuing with the issue?

**Comment by novemberborn** [comment] 2017-06-09 13:28
I think you need to `throw new AssertionError()`. That'll reject the `intermediate` promise which [causes the test to record the failure](https://github.com/avajs/ava/blob/c4c5e7bb3ec43726c03d9834f55e157c5feacf8f/lib/test.js#L171). That should fix the test in `test/assert.js` as well.

> Is it OK if I'm continuing with the issue?

Seems to me you already solved it! 🥇  Looking forward to the PR.

**Closed** 2017-06-13 18:48 UTC
Labels: assigned, bug, help wanted
