### ISSUE TITLE
Provide a convenience API for testing error constructor and message

### ISSUE THREAD

**Issue by gajus** [avajs/ava#1362] opened 2017-04-18 19:57 UTC
## Description

The current API:

```js
.throws(function|promise, [error, [message]])
```

only allows to define constructor of the error and requires to test message separately, e.g.

```js
const error = await t.throws(createReservation(undefined, parameters, context), UserError);

t.true(error.message === 'Ticket selection cannot be empty.');
```

> By the way, `.throws(function|promise, [error, [message]])` is slightly misleading.
> At first I thought the third parameter is the *error* message, i.e.
> `t.throws(createReservation(undefined, parameters, context), 'Ticket selection cannot be empty.');`.

It would be convenient to be able to construct the error as such:

```js
await t.throws(createReservation(undefined, parameters, context), new UserError(Ticket selection cannot be empty.));

```

In such case, ava would need to check that the constructor of the object and the message match.

**Comment by sindresorhus** [comment] 2017-04-19 05:19
Duplicate of https://github.com/avajs/ava/issues/1047. I agree it's sub-optimal. You should be able to assert the different specifics of an error in one assertion. See my proposal https://github.com/avajs/ava/issues/1047#issuecomment-261483195 and add your thoughts there.

**Closed by sindresorhus** 2017-04-19 05:19 UTC
