### ISSUE TITLE
faulty assertion for React component with React.Fragment causes concordance to crash

### ISSUE THREAD

**Issue by iamstarkov** [avajs/ava#1939] opened 2018-09-18 12:34 UTC
### Test Source

This one works correctly

```js
import React from 'react';
import { shallow } from 'enzyme';
import test from 'ava';

const ConcordanceBugDemoOkay = () => <div />;
test('demo okay', t => {
  const wrapper = shallow(<ConcordanceBugDemoOkay />);
  t.falsy(wrapper);
});
```

this one does not work correctly:

```js
import React from 'react';
import { shallow } from 'enzyme';
import test from 'ava';

const ConcordanceBugDemoNotOkay = () => <React.Fragment />;
test('demo', t => {
  const wrapper = shallow(<ConcordanceBugDemoNotOkay />);
  t.falsy(wrapper);
});
```

and causes concordance to crash because it tries to concatenate string with Symbol.

### Error Message & Stack Trace

```
/Users/iamstarkov/projects/project/node_modules/concordance/lib/formatUtils.js:6

Error thrown in test:

TypeError {
  message: 'Cannot convert a Symbol value to a string',
}

Object.wrap [as wrapFromTheme] (node_modules/concordance/lib/formatUtils.js:6:25)
Object.formatName (node_modules/@concordance/react/lib/elementFactory.js:109:29)
Object.finalize (node_modules/@concordance/react/lib/elementFactory.js:133:29)
formatDescriptor (node_modules/concordance/lib/format.js:85:42)
Object.format (node_modules/concordance/lib/format.js:99:10)
```

### Config

N/A

### Command-Line Arguments

N/A

## Environment

```
Node.js v8.12.0
darwin 17.7.0
ava --version # 1.0.0-beta.8
npm --version # 6.4.1
yarn --version # 1.9.4
```

**Comment by novemberborn** [comment] 2018-09-18 12:39
Which React version is this?

**Comment by iamstarkov** [comment] 2018-09-18 12:40
I think I have a fix

**Comment by novemberborn** [comment] 2018-09-18 12:41
Looks like the name is now a symbol, rather than a string. Should be fixable in `@concordance/react`.

**Comment by iamstarkov** [comment] 2018-09-18 12:42
is it good enough fix?

**Comment by iamstarkov** [comment] 2018-09-18 12:43
it will work for all versions of react with Fragment

**Comment by novemberborn** [comment] 2018-09-18 12:44
We should fix this at the call site: https://github.com/concordancejs/react/blob/7f8101f6f67fd03249af28828b16e69e9d914b60/lib/elementFactory.js#L109

Assuming the symbol is registered, we could detect it and then use `React.Fragment` as the name. But there should be a fallback for other symbols.

**Comment by iamstarkov** [comment] 2018-09-18 12:54
well, Im sorry. you lost me on registered symbol. 

But I still think it will be a good idea to defend lib/formatUtils.js@wrap against non string instances. What do you think?

**Comment by novemberborn** [comment] 2018-09-18 13:01
> well, Im sorry. you lost me on registered symbol.

See https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Symbol/for.

> But I still think it will be a good idea to defend lib/formatUtils.js@wrap against non string instances. What do you think?

No, consider it typed as taking `value` as a string. The problem is in `@concordance/react`. I'd been meaning to take a look at that. There's a flurry of Concordance activity all of a sudden! 😀

**Comment by iamstarkov** [comment] 2018-09-18 19:20
I looked into it for quite some time and cant figure out how to do it =(

**Comment by novemberborn** [comment] 2018-09-23 17:08
This should be fixed with https://github.com/concordancejs/react/pull/14.

I have one more PR that needs to land in `concordance` itself, and then I need to do the upgrade dance to get these changes into AVA itself.

**Comment by novemberborn** [comment] 2018-09-30 15:58
@iamstarkov the necessary changes are landing in #1942.

**Comment by iamstarkov** [comment] 2018-10-01 10:16
@novemberborn nice

**Closed** 2018-10-13 13:07 UTC
Labels: bug
