### ISSUE TITLE
Magic assert obstructs helpful error for incorrect test usage

### ISSUE THREAD

**Issue by sindresorhus** [avajs/ava#1256] opened 2017-02-11 16:34 UTC
```js
import test from 'ava';

test(() => {
	test(t => {
		t.pass();
	});
});
```

## AVA 0.17

```
Error: All tests and hooks must be declared synchronously in your test file, and cannot be nested within other tests or hooks.
  wrappedFn (node_modules/option-chain/index.js:36:14)
  Test.fn (magic-assert-bug.js:4:2)
```

## AVA 0.18

```
  1 failed

  [anonymous]
  node_modules/option-chain/index.js:36

   35:       }
   36:       return fn.apply(ctx || this, args);
   37:     }

  Error: All tests and hooks must be declared synchronously in your test file, and cannot be nested within other tests or hooks.

  wrappedFn (node_modules/option-chain/index.js:36:14)
  Test.fn (magic-assert-bug.js:4:2)
```

## AVA master

```js
  1 failed/Users/sindresorhus/dev/ava/lib/cli.js:177
					throw err;
					^

Error: ENOENT: no such file or directory, open '/Users/sindresorhus/dev/private/ava-playground/Users/sindresorhus/dev/ava/node_modules/option-chain/index.js'
    at Error (native)
    at Object.fs.openSync (fs.js:640:18)
    at Object.fs.readFileSync (fs.js:508:33)
    at module.exports (/Users/sindresorhus/dev/ava/lib/code-excerpt.js:15:20)
    at runStatus.errors.forEach (/Users/sindresorhus/dev/ava/lib/reporters/mini.js:191:22)
    at Array.forEach (native)
    at MiniReporter.finish (/Users/sindresorhus/dev/ava/lib/reporters/mini.js:178:21)
    at Logger.finish (/Users/sindresorhus/dev/ava/lib/logger.js:38:28)
    at api.run.then.runStatus (/Users/sindresorhus/dev/ava/lib/cli.js:170:12)
From previous event:
    at Object.exports.run.err [as run] (/Users/sindresorhus/dev/ava/lib/cli.js:169:5)
    at Object.<anonymous> (/Users/sindresorhus/dev/ava/cli.js:22:24)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:509:3
```

I don't think the behavior in 0.18 is the best either. Having magic assert for this is not very helpful. Better to keep it like it was in 0.17.

Any way we can hide the `wrappedFn (node_modules/option-chain/index.js:36:14)` too? It's not useful there.

// @vadimdemedes

**Comment by vadimdemedes** [comment] 2017-02-11 17:03
I think it's a duplicate of https://github.com/avajs/ava/issues/1231, since the fix will be the same for both issues. The plan is to skip code excerpts and magic-assert output for all errors coming from `node_modules` directory.

**Comment by sindresorhus** [comment] 2017-02-12 18:47
@vadimdemedes Regardless, should magic assert be shown on non-assertion errors?

**Comment by vadimdemedes** [comment] 2017-02-12 19:02
Oh, right, that's a good point. Will add a check to detect the assertion error. Should be not so strict though, to support chai, expect, etc.

**Comment by sindresorhus** [comment] 2017-02-12 19:20
[Pretty sure](https://github.com/chaijs/assertion-error/blob/b36f593951c1487fa33747c9911025734923f28c/index.js#L91) all of them are `err.name === 'AssertionError`. You could maybe check for `actual`, `expected` properties too.

**Comment by novemberborn** [comment] 2017-02-16 17:58
> Oh, right, that's a good point. Will add a check to detect the assertion error.

We're only formatting the error if the `showOutput` flag is set: https://github.com/avajs/ava/blob/8d6f9bc2e2ed02b39e32cdf2b952b680c3b19338/lib/reporters/mini.js#L197:L198

That only happens for our own assertion methods: https://github.com/avajs/ava/blob/8d6f9bc2e2ed02b39e32cdf2b952b680c3b19338/lib/assert.js#L29

> Should be not so strict though, to support chai, expect, etc.

We'd need to validate whether thrown errors have the required properties and then set the flag. I don't think Chai assertions do this. I suppose we could open this as a feature request?

---

In all this is a duplicate of #1268.

**Closed by novemberborn** 2017-02-16 17:58 UTC
Labels: bug

**Comment by sindresorhus** [comment] 2017-02-20 05:57
> I suppose we could open this as a feature request?

👍
