### ISSUE TITLE
after and after.always don't run in 1.0.0-beta.6

### ISSUE THREAD

**Issue by jacobg** [avajs/ava#1870] opened 2018-07-17 13:04 UTC
after and after.always don't run in 1.0.0-beta.6
They're simply skipped, whether the test is successful or not.

It works totally fine in 0.25.0

**Comment by novemberborn** [comment] 2018-07-18 08:40
@jacobg oh no, that sounds bad! There have been a lot of changes internally since 0.25, but I'd be surprised if something like that slipped through.

I'm a bit busy at the moment, perhaps you could write a simple reproduction? A test, an `after`, and an `after.always`, all of them perhaps calling `console.error` with a message?

Thanks!

**Comment by novemberborn** [comment] 2018-07-21 15:38
I can't reproduce this:

```js
import test from 'ava'

test('test', t => {console.error('test'); t.pass()})
test.after(() => console.error('after'))
test.after.always(() => console.error('after.always'))
```

```console
❯ npx ava test.js -v

test
  ✔ test
after
after.always

  1 test passed
```

Closing this for now. If you could share a reproduction that'd be great.

**Closed by novemberborn** 2018-07-21 15:38 UTC
Labels: bug, question
