### ISSUE TITLE
Is --require work like mocha --require (for using ts-node)?

### ISSUE THREAD

**Issue by unional** [avajs/ava#905] opened 2016-06-07 18:36 UTC
I want to use `ts-node` to run test files written in TypeScript through `ava`. This would skip the extra compilation step and make things easier.

Specifically, I want to do something similar to this: https://github.com/TypeStrong/ts-node#mocha

```sh
mocha --require ts-node/register [...args]
```

Currently, when I try it, it failed with "Couldn't find any files to test":

```sh
ava --require ts-node/register "**/*.spec.ts"

   1 exception


   x Couldn't find any files to test
```

My guess is `ava is looking for `.js` files or tries to manage the `.ts` files directly.

Would this be a possibility? 🌷

**Comment by jamestalmage** [comment] 2016-06-07 19:04
AVA looks for `.js` specifically.

Duplicate of https://github.com/avajs/ava/issues/631

**Closed by jamestalmage** 2016-06-07 19:04 UTC
