### ISSUE TITLE
Feature: support unicode

### ISSUE THREAD

**Issue by unional** [avajs/ava#1163] opened 2016-12-22 23:56 UTC
ava: 0.17

```js
// main.js
var chalk = require('chalk')
console.log(chalk.red('something'))

// test.spec.js
var test = require('ava').default
var chalk = require('chalk')
test('unicode doesnot work', t => {
  console.log(chalk.red('something'))
})
```

`node main.js` works, while `ava` prints in black/white.
  
[This issue](https://github.com/avajs/ava/issues/1039) seems to suggest it works, but it doesn't for me.

**Comment by mightyiam** [comment] 2016-12-23 00:08
Unless chalk adds unicode, I do not see unicode here... Enlighten me, because I must be missing something.

**Comment by unional** [comment] 2016-12-23 01:55
Sorry, maybe not unicode, but the color is not showing. What is the proper name of it? Please feel free to chagne the title.

**Comment by vadimdemedes** [comment] 2016-12-23 21:37
Closing as a duplicate of https://github.com/avajs/ava/issues/1124.

**Closed by vadimdemedes** 2016-12-23 21:37 UTC
