### ISSUE TITLE
Support ES modules natively with transform-es2015-modules-commonjs

### ISSUE THREAD

**Issue by bfred-it** [avajs/ava#1453] opened 2017-07-14 05:20 UTC
It'd be great to start natively supporting ES modules via [`transform-es2015-modules-commonjs`](https://www.npmjs.com/package/babel-plugin-transform-es2015-modules-commonjs)

In [sindresorhus/refined-github](https://github.com/sindresorhus/refined-github) we've been using this plugin just for AVA support: 

https://github.com/sindresorhus/refined-github/blob/9343190ffbc13e0cbeab79b1382135859b4c8afe/package.json#L78

**Comment by novemberborn** [comment] 2017-07-16 13:13
Yes, it is included through our [`stage-4`](https://github.com/avajs/babel-preset-stage-4) preset, for test files. AVA does not transpile sources though, which I think is what you're referring to?

**Comment by bfred-it** [comment] 2017-07-16 17:53
Yeah, sorry if I wasn't more specific

**Comment by novemberborn** [comment] 2017-07-17 07:21
There's a plan for letting AVA transpile sources, but we haven't made much progress yet: https://github.com/avajs/ava/blob/master/docs/specs/001%20-%20Improving%20language%20support.md

Will close this as a duplicate of sorts.

**Closed by novemberborn** 2017-07-17 07:21 UTC
