### ISSUE TITLE
Cannot call `test` with async function bound to `run` because in the return value

### ISSUE THREAD

**Issue by gajus** [avajs/ava#1785] opened 2018-05-03 11:19 UTC
## Description

Flow complains use of `async` test functions.

### Test Source

```js
// @flow

import test from 'ava';

test('reads files', async (t) => {});

```

### Error Message & Stack Trace

```
Error ┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈ test/utilities/bufferBody.js:5:33

Cannot call test with async function bound to run because in the return value:
 • Either property @@iterator is missing in Promise [1] but exists in $Iterator [2].
 • Or property subscribe is missing in Promise [1] but exists in ObservableLike [3].

     test/utilities/bufferBody.js
      2│
      3│ import test from 'ava';
      4│
 [1]  5│ test('reads files', async (t) => {});
      6│

     node_modules/ava/index.js.flow
 [2] 20│ 	| Iterator<any>
 [3] 21│ 	| ObservableLike;

```

### Config

N/A

### Command-Line Arguments

N/A

## Relevant Links

N/A

## Environment

Tell us which operating system you are using, as well as which versions of Node.js, npm, and AVA. Run the following to get it quickly:

```bash
Node.js v10.0.0
darwin 17.4.0
0.25.0
5.6.0

```

**Comment by novemberborn** [comment] 2018-05-04 08:50
Which Flow version is this? Definitions have been completely rewritten, does this occur with [`ava@next`](https://github.com/avajs/ava/releases/tag/v1.0.0-beta.4)?

**Comment by hallettj** [comment] 2018-05-04 14:39
I can reproduce the error with Flow v0.71.0 and both AVA v0.25.0 and AVA v1.0.0-beta.4. But the problem is fixed by #1778.

**Comment by hallettj** [comment] 2018-05-04 14:47
By the way, it is possible to back-port the fix from #1778 to the v0.25.0 by making nearly the same change:

**Comment by novemberborn** [comment] 2018-05-07 13:28
Thanks for clarifying @hallettj.

I'm not really interested in backporting to v0.25.0. If it hadn't been for Babel 7 being in beta we'd be at v0.29.0 by now, and we wouldn't have backported anything either.

**Closed by novemberborn** 2018-05-07 13:28 UTC

**Comment by gajus** [comment] 2018-05-07 14:13
> I'm not really interested in backporting to v0.25.0. If it hadn't been for Babel 7 being in beta we'd be at v0.29.0 by now, and we wouldn't have backported anything either.

So whats the solution?

**Comment by novemberborn** [comment] 2018-05-07 16:04
@gajus #1778 has landed, so you could install a Git dependency from `master` until the next release is out. That may be next weekend. Or downgrade Flow.
