### ISSUE TITLE
Simplify t.throws()

### ISSUE THREAD

**Issue by novemberborn** [avajs/ava#1047] opened 2016-09-23 13:53 UTC
This is my proposal for resolving #661. In short I want to stop deferring to https://nodejs.org/api/assert.html#assert_assert_throws_block_error_message and remove various parameter overloads that are currently supported by the assertion.

Here's what I'd like to support:

``` js
t.throws(fn) // Throws an Error (or subclass thereof)
t.throws(fn, SyntaxError) // Throws a SyntaxError (or subclass thereof)
t.throws(fn, 'string') // Throws an Error (or subclass thereof), whose .message === 'string'
t.throws(fn, /regexp/) // Throws an Error (or subclass thereof), whose /regexp/.test(err.message) === true
```

If you need to test the errors class and message you should use the `t.throws` return value:

``` js
const err = t.throws(fn, SyntaxError)
t.true(err.message === 'expecting integer')
```

Passing anything other than `undefined`, functions, strings or regular expressions as the second argument results in an `TypeError` from `t.throws()` itself.

The first argument is allowed to be a promise or observable, as is any return value from the `fn` call. Of course this makes `t.throws` asynchronous, so users may need to do:

``` js
const err = await t.throws(fn)
```

---

Questions:
1. Does `t.throws(fn, Constructor)` require the thrown value to be an `Error`? For example:
   
   ``` js
   t.throws(() => { throw 'foo' }, String) // Is this allowed?
   ```
2. Should `t.throws(fn, 'string')` and `t.throws(fn, /regexp/)` be supported at all, or would it be preferable to dereference the error and then use another assertion?
   
   ``` js
   const err = t.throws(fn)
   t.true(err.message === 'expecting integer')
   ```
3. Is there a need for `t.throws(fn, SyntaxError, 'string')` and `t.throws(fn, SyntaxError, /regexp/)`
4. Does anybody have experience with / examples of asserting `Error` instances across contexts?

**Comment by vdemedes** [comment] 2016-09-29 08:13
I absolutely support your proposal!

Answers to your questions:

1. I don't think it should be allowed. ESLint's docs on `no-throw-literal` rule explain it best:

> It is considered good practice to only throw the Error object itself or an object using the Error object as base objects for user-defined exceptions. The fundamental benefit of Error objects is that they automatically keep track of where they were built and originated.

Services like BugSnag, Sentry, Rollbar, etc will provide zero information, if code throws strings, instead of Error objects.

2. I think they should be supported, with behavior exactly like you outlined in your first code example:

```js
t.throws(fn, 'string') // Throws an Error (or subclass thereof), whose .message === 'string'
t.throws(fn, /regexp/) // Throws an Error (or subclass thereof), whose /regexp/.test(err.message) === true
```

I use this way constantly and find it very convenient.

3. I think this would also be a nice thing to have, but not insisting on this one. Let's hear from others whether they use this way or not.

4. Didn't completely understand the question, mind providing a quick example?

**Comment by fearphage** [comment] 2016-10-02 14:13
The current implementation seems to almost match your proposal. `t.throws(fn, type, message)` doesn't work (`0.16.0`). I can't tell if this is a regression or a mix up in the documentation. I went back 10 or so commits and never saw where this worked. There are no tests for this format either.

I was coming here to file that bug report and submit the PR, but I won't if you're planning to remove it altogether.

**Comment by novemberborn** [comment] 2016-10-07 13:58
Conclusions so far:

> Does `t.throws(fn, Constructor)` require the thrown value to be an `Error`?

Yes.

> Should `t.throws(fn, 'string')` and `t.throws(fn, /regexp/)` be supported at all, or would it be preferable to dereference the error and then use another assertion?

We'll support this interface.

> Is there a need for `t.throws(fn, SyntaxError, 'string')` and `t.throws(fn, SyntaxError, /regexp/)`

Leaning towards not supporting this.

---

@vdemedes 

>> Does anybody have experience with / examples of asserting `Error` instances across contexts?
>
> Didn't completely understand the question, mind providing a quick example?

```js
const err1 = new Error()
const err2 = vm.runInNewContext('new Error()')
err1 instanceof Error // true
err2 instanceof Error // false
```

---

@fearphage yea AVA just uses Node.js' API, and it gets messy fast. Hence this proposal.

**Comment by fearphage** [comment] 2016-10-07 14:11
> > Is there a need for t.throws(fn, SyntaxError, 'string') and t.throws(fn, SyntaxError, /regexp/)

> Leaning towards not supporting this.

Is it difficult to code or reason about? Just a preference? I'm just curious.

If we're target an arity of 2, what about this as an option?

```js
t.throws(fn, error => {
  // insert error assertions
});
```

I like the encapsulation of the assertions related to the thrown error.

**Comment by novemberborn** [comment] 2016-10-07 14:14
> Is it difficult to code or reason about? Just a preference? I'm just curious.

The assertion becomes overly complex again, which is what we're trying to move away from.

> If we're target an arity of 2, what about this as an option?
> 
> ```js
> t.throws(fn, error => {
>   // insert error assertions
> });
> ```
>
> I like the encapsulation of the assertions related to the thrown error.

That'll be hard to distinguish from `t.throws(fn, Constructor)`.

**Comment by jfmengels** [comment] 2016-10-13 09:01
I like the proposal :)

> 1. Does t.throws(fn, Constructor) require the thrown value to be an Error?

Yes. That is a best practice, or rather, using a string is a bad practice, and we should help the user remove that bad practice from their code IMO.
We should also (and I don't remember whether this is already something that we're doing) fail and show an error when the thrown error is a string and not an Error.
It's a bit different if an underlying library throws a string, but even then it should be simple for the user to get around that and do a normal try/catch instead.

> 2. Should t.throws(fn, 'string') and t.throws(fn, /regexp/) be supported at all, or would it be preferable to dereference the error and then use another assertion?

That is common enough to keep IMO.

> 3. Is there a need for t.throws(fn, SyntaxError, 'string') and t.throws(fn, SyntaxError, /regexp/)

I don't custom Error types that much. I think it's rare enough and simple enough to get around it
```js
const err = t.throws(fn, 'string');
t.true(err instanceof SyntaxError);
```

> 4. Does anybody have experience with / examples of asserting Error instances across contexts?

No :/

> ----


Your proposal does not support a `message` parameter, to show when the assertion fails. You could simply add it to the list or parameters, but then you'd get an awkward `t.throws(fn, undefined, message)` when you don't want to assert anything about the thrown error. It's awkward/ugly, but I would still support this as it resembles the other APIs.

**Comment by novemberborn** [comment] 2016-10-14 14:18
> We should also (and I don't remember whether this is already something that we're doing) fail and show an error when the thrown error is a string and not an Error.

Yes that's implied.

> From what I see, you're proposing the removal of the message too? That would make it inconsistent with the other APIs. Not sure I agree here.

Oh no! Forgot to add that…

I think that rules out syntax like `t.throws(fn, SyntaxError, 'string')`, since that collides with `t.throws(fn, SyntaxError, 'message')`. Padding it is just annoying (`t.throws(fn, SyntaxError, undefined, 'message')`. Though you would need to pad `t.throws(fn, undefined, 'message')`. I think that's OK though.

**Comment by sindresorhus** [comment] 2016-11-18 09:11
Alternative proposal.

Make it `t.throws(fn, matchers, [message]);`, where `matchers` is an object of different matchers that all has to match. Matchers can be string or regex.

This could easily be an addition to supporting string/regex/constructor in the second argument, for backwards compatibility.

For example:

```js
t.throws(() => foo(), {
	constructor: RangeError,
	message: /unicorn pasta is/
});
```

Compared to the current way:

```js
const err = t.throws(() => foo(), /unicorn pasta is/);
t.true(err instanceof RangeError);
```

Possible matchers `constructor`, `message`. Could also consider supporting `name` for when you don't have easy access to the constructor function. Maybe also `stack` if you want to ensure something is part of it, though I don't think I've ever needed that.

Benefits of this is that it makes everything explicit. No more wondering for users what `t.throws(() => foo(), 'Unicorn')` matches against - Is it the name, type, or message. There's also benefit in being able to specify all the constraints directly instead of in separate calls later, like potential for a better diff.

**Comment by novemberborn** [comment] 2016-11-18 10:46
I like it!

**Comment by sholladay** [comment] 2017-02-11 17:32
I like Sindre's proposal. It would still return the error for extra assertions, right? Let's say I also want to ensure that multi-line error messages never exceed a certain width, for friendly terminal display. Would it look like this?

```js
const err = t.throws(() => foo(), {
    constructor: RangeError,
    message: /unicorn pasta is/
});
t.is(longestLine(err.message), 80);
```

I will note that there is a much simpler approach to solve the call site ambiguity problem. Just support only constructors in the second argument, since that's the only type that is non-ambiguous for what it is matching. Delegate everything else to `t.is()`, `t.regex()`, etc.

**Comment by sindresorhus** [comment] 2017-02-11 17:36
> It would still return the error for extra assertions, right?

Yes

> Just support only constructors in the second argument, since that's the only type that is non-ambiguous for what it is matching. Delegate everything else to t.is(), t.regex(), etc.

It creates verbose code for common cases though. The most common case is wanting to ensure the error is the correct type and has the correct message. I think we should optimize for that.

**Comment by AlexTes** [comment] 2017-03-21 08:57
Love this proposal. Eliminating the constructor vs. validator function ambiguity would've saved me a lot of time and [confusion](https://github.com/nodejs/node/issues/9373).

Is there still something to be done on the 'question' side of things? It's hard to give a helpful push without a clear direction 😄.

**Comment by novemberborn** [comment] 2017-03-21 10:06
@AlexTes we can go with @sindresorhus' proposal: https://github.com/avajs/ava/issues/1047#issuecomment-261483195

Match `constructor` by reference, `name` by equality, and `message` either by testing a regular expression or string equality.

**Comment by sindresorhus** [comment] 2017-03-21 10:14
I had the need the other day to match against a custom error property. Should we support that too?

**Comment by novemberborn** [comment] 2017-03-21 11:35
> I had the need the other day to match against a custom error property. Should we support that too?

I think that's better served by assigning the thrown error to a variable and asserting on that.

**Comment by AlexTes** [comment] 2017-03-21 11:54
@sindresorhus I feel the consensus was around supporting common use-cases for error comparison. In other words, offer shortcuts to common comparisons but keep the API surface small as one can already do any comparison with the returned error. 'The other day' only tells us about recency, how about frequency? I think this decision is a tricky balance between frequency, the cost of doing without, and diff potential. Personally I'm leaning towards leaving it out, like novemberborn.

@novemberborn I'd actually lean against Sindre's suggestion of possibly adding a `name` matcher. Can I ask, when would a name be preferred over a constructor? I can't think of anything. That for me makes this an infrequent help at best, which for simplicity's sake I would then leave out.

One more detail I'd like to bring to the attention of the jury 😄. Sindre Proposal also adds backwards compatibility for the second argument, when not a matcher object, of type string / regex / constructor.

1. Regex
Match on string representation of actual error.

2. Constructor
Match constructor function by reference.

3. String
Currently [unsupported](https://nodejs.org/api/assert.html#assert_assert_throws_block_error_message) by Node. Is this one to be an exact match of the string representation of the error? Or just the message of the error?

4. Validation Function
Currently supported by Node. We drop it. The reasoning being this is again custom and not commonly useful checking. Thus up to the user to do with the returned error.

My fingers are starting to itch to write the implementation on this one 😛.

**Comment by novemberborn** [comment] 2017-03-21 13:56
@AlexTes 

> Can I ask, when would a name be preferred over a constructor?

It's usually better to compare errors using their `.name`. `if (error instanceof MyError)` doesn't necessarily work across VM contexts, for example. Libraries might also not bother exporting their error constructors.

> String
> Currently unsupported by Node. Is this one to be an exact match of the string representation of the error? Or just the message of the error

It's currently [implemented as comparing the message](https://github.com/avajs/ava/blob/3da8603b87ae43a77f581738233ea98c3de5a10f/lib/assert.js#L135). We should do the same with the regular expression argument, IMO.

Historically the problem with the `throws` assertion is that it tries to do too many things, making it hard to understand what you're actually testing. Running a regular expression against the string representation of an error is an example of that. I didn't even know that's how it worked!

Personally I don't think we should maintain backwards compatibility, given how confusing `throws` is.

**Comment by sholladay** [comment] 2017-03-21 14:25
> I'd actually lean against Sindre's suggestion of possibly adding a name matcher. Can I ask, when would a name be preferred over a constructor?

I don't personally need this feature much, but for sake of argument...

Say `myApp()` uses a database under the hood and potentially rejects with various `DatabaseError`s. You probably want to make assertions about failure cases for `myApp()` working with the database, but the relevant error constructor does not live in your app and very well may not be exposed by the database driver library (it is uncommon to export all such classes).

You still need to distinguish between different types of errors and, without the constructor, `name` is the preferred way to ID an error (should be more stable than `message`). Changes to these are arguably semver major, so you should probably test them. This is the best you can do without the constructor.

```js
test(async (t) => {
    const option = {
        databaseName : 'somethingThatDoesNotExist'
    };
    t.throws(myApp(option), {
        name : 'DatabaseNotFoundError'
    });
});
```

**Comment by AlexTes** [comment] 2017-03-21 14:33
Ah, as shown in your example earlier @novemberborn. I understand the need and even preference for `name` now.

I didn't know Ava's `assert` has seen some big change. Congrats on the big PR! I read through ava's assert module two weeks back, since then #1302 landed. Forgive me for missing Ava no longer almost directly relies on Node's `assert`. 

Comparing just the message makes a lot of sense to me if we already support the name separately. It would break with [Node's behavior](https://github.com/sindresorhus/core-assert/blob/master/index.js#L290). I have no idea how to weigh the two, though I feel your argument to make it simpler is compelling.
> I didn't even know that's how it worked!

Happy to be able to contribute something small 😄.

**Comment by novemberborn** [comment] 2017-03-21 15:05
@AlexTes thanks! Be sure to check out #1314 which contains a few more changes.

> without the constructor, name is the preferred way to ID an error (should be more stable than message).

@sholladay, I think Node.js is moving to standardizing error codes, though I couldn't find a definitive proposal on that. File system errors have `code` and `errno` properties. We should support whatever practice Node.js settles on, though we can add that later.

**Comment by StoneCypher** [comment] 2017-07-05 22:09
I really don't think we should be excluding valid `throw`s just because a linter rule claims it's bad practice.

I lost nearly an entire day because I threw a string, which is fully valid, and `.throws` broke instead of catching it or telling me what it didn't like

**Comment by StoneCypher** [comment] 2017-07-05 22:10
I don't really think my commentary belongs on this issue, which isn't about throwing strings in any meaningful way, but a maintainer closed the valid and appropriate issue about that explicitly in favor of this one

I apologize for what seems to me to be unnecessarily changing the subject

**Comment by novemberborn** [comment] 2017-07-06 07:24
@StoneCypher When we implement `t.throws()` in AVA directly we'll make sure it explains why a thrown value still causes the assertion to fail.

**Comment by novemberborn** [comment] 2017-07-06 07:26
Oh, I see that's #1440.

**Comment by StoneCypher** [comment] 2017-07-06 16:27
Thanks.  That seems ideal to me.

**Closed** 2018-02-13 18:31 UTC
Labels: enhancement, help wanted, scope:assertions
